#!/usr/bin/env python3

import sys
import typing as ty
from argparse import (
    ArgumentParser,
    ArgumentDefaultsHelpFormatter,
    SUPPRESS)


def parse_args():
    default_py = \
        'python.exe' \
        if sys.platform == 'win32' \
        else 'python3'

    parser = ArgumentParser(
        formatter_class=ArgumentDefaultsHelpFormatter)
    parser.add_argument(
        '--antlr4-jar', type=str,
        help='antlr4 jar location',
        default=SUPPRESS,
        required=True
    )
    parser.add_argument(
        '--python3-exec', type=str,
        help='python3 file location',
        default=default_py
    )
    return parser.parse_args()


def main():
    args = parse_args()
    properties: dict[str, ty.Callable[[], str]] = {
        'antlr4.jar': lambda: args.antlr4_jar,
        'python3.exec': lambda: args.python3_exec
    }
    with open('build.local.properties', 'w', encoding='utf-8') as prop_file:
        prop_file.write(
            '# generated by configure.py. Do not edit manually\n')
        for k, prop_function in properties.items():
            prop_file.write(f'{k}={prop_function()}')
            prop_file.write('\n')
    return 0


if __name__ == '__main__':
    sys.exit(main() or 0)
