[tool.pylint.'MESSAGES CONTROL']
disable = [
    'missing-module-docstring',
    'missing-function-docstring',
    'missing-class-docstring',
    'no-else-return',
    'too-few-public-methods',
    'trailing-comma-tuple',
    'trailing-newlines'
]

[tool.isort]
src_paths = ['src']
